### EXAMPLE DOCKER COMPOSE ###
version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /audiobooks:/audiobooks
      - /metadata:/metadata
      - /config:/config
